### ISSUE TITLE
Why was the Message Analyzer been retired at all?

### ISSUE THREAD

**Issue by Philosoph228** [riverar/messageanalyzer-archive#3]

**Comment by riverar** [comment]
I can't answer that, sorry!

**Comment by Philosoph228** [comment]
@riverar, understood. But the reply little bit unclear. You can't answer that because you don't know actually, or explanation of product lifecycle is not part of your responsibilities, or because it is a product strategy secret? You can still point us in the right direction by giving an explanation why you can't. If the the statement of MVP alumni to stop - it will be more clear to stop finding answer further.
